[package]
name = "audiomodder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
serde = "1.0.152"
loom = "0.5.6"